/**
 * Topcoder Meta Services REST API
 * REST API for Topcoder Meta Services.  This describes a service that can give information on other services existing on Topcoder.  Available service links can be listed by sending GET request. Also, each service can return links to further services in their responses.  ### Pagination   Requests that return multiple items will be paginated to 20 items by default. You can specify   further pages with the ```page``` parameter. You can also set a custom page   size up to 100 with the ```perPage``` parameter.    Pagination response data is included in http headers. By Default, the response header contains links with ```next```, ```last```, ```first```, ```prev``` resource links. 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: support@topcoder.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TopcoderMetaServicesRestApi) {
      root.TopcoderMetaServicesRestApi = {};
    }
    root.TopcoderMetaServicesRestApi.EventPayload = factory(root.TopcoderMetaServicesRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EventPayload model module.
   * @module model/EventPayload
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>EventPayload</code>.
   * The event payload entity.
   * @alias module:model/EventPayload
   * @class
   * @param topic {String} Topic name should be a dot separated fully qualified name i.e. domain.type.operation. 
   * @param originator {String} Service repository name, from where message is published. 
   * @param timestamp {Date} Timestamp at which message is published. The date-time notation as defined by RFC 3339, section 5.6, for example, 2018-04-13T00:00:00Z 
   * @param mimeType {String} Mime-type for 'payload'. 
   * @param payload {Object} Actual payload depending on mime-type for consumer. 
   */
  var exports = function(topic, originator, timestamp, mimeType, payload) {
    var _this = this;

    _this['topic'] = topic;
    _this['originator'] = originator;
    _this['timestamp'] = timestamp;
    _this['mime-type'] = mimeType;
    _this['payload'] = payload;
  };

  /**
   * Constructs a <code>EventPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventPayload} obj Optional instance to populate.
   * @return {module:model/EventPayload} The populated <code>EventPayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('topic')) {
        obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
      }
      if (data.hasOwnProperty('originator')) {
        obj['originator'] = ApiClient.convertToType(data['originator'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
      }
      if (data.hasOwnProperty('mime-type')) {
        obj['mime-type'] = ApiClient.convertToType(data['mime-type'], 'String');
      }
      if (data.hasOwnProperty('payload')) {
        obj['payload'] = ApiClient.convertToType(data['payload'], Object);
      }
    }
    return obj;
  }

  /**
   * Topic name should be a dot separated fully qualified name i.e. domain.type.operation. 
   * @member {String} topic
   */
  exports.prototype['topic'] = undefined;
  /**
   * Service repository name, from where message is published. 
   * @member {String} originator
   */
  exports.prototype['originator'] = undefined;
  /**
   * Timestamp at which message is published. The date-time notation as defined by RFC 3339, section 5.6, for example, 2018-04-13T00:00:00Z 
   * @member {Date} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * Mime-type for 'payload'. 
   * @member {String} mime-type
   */
  exports.prototype['mime-type'] = undefined;
  /**
   * Actual payload depending on mime-type for consumer. 
   * @member {Object} payload
   */
  exports.prototype['payload'] = undefined;



  return exports;
}));


